#!/usr/bin/env -S python3 -B
# -*- coding: utf-8 -*-

# Copyright (c) 2020 Mario Mlačak, mmlacak@gmail.com
# Licensed under GNU GPL v3+ license. See LICENSING, COPYING files for details.


DEFAULT_ARROW_INVERSE_WIDTH_RATIO = 12.0 # Compared to field size.
DEFAULT_ARROW_POINTY_BIT_RATIO = 1.5 # Compared to arrow width. # 80.0

DEFAULT_FONT_NAME = 'sans' # "sans bold"
DEFAULT_FONT_SIZE_INVERSE_RATIO = 5.0 # Compared to field size.
DEFAULT_FONT_SIZE = 1.0 / DEFAULT_FONT_SIZE_INVERSE_RATIO
DEFAULT_FONT_SPACER = 0.01

DEFAULT_FIELD_MARKER_INVERSE_WIDTH_RATIO = 5.0 # Compared to field size.
DEFAULT_FIELD_MARKER_SIZE = 1.0 / DEFAULT_FIELD_MARKER_INVERSE_WIDTH_RATIO

DEFAULT_LINE_WIDTH = 0.019
DEFAULT_TEXT_OUTLINE_WIDTH = DEFAULT_LINE_WIDTH / 2.0

DEFAULT_PIECE_WITH_CHIP_TRANSLATION = 0.11

DEFAULT_IMAGE_FOLDER_REL_PATH = '../gfx/' # '../tmp/'
DEFAULT_FILE_EXT = '.png'
