// Copyright (c) 2021 Mario Mlačak, mmlacak@gmail.com
// Licensed under GNU GPL v3+ license. See LICENSING, COPYING files for details.

#ifndef __CC_SETUP_BOARD_H__
#define __CC_SETUP_BOARD_H__

#include "cc_piece.h"
#include "cc_variant.h"


extern CcPieceTagType const CC_SETUP_BOARD_CLASSICAL_CHESS[ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS ][ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS ];

extern CcPieceTagType const CC_SETUP_BOARD_CROATIAN_TIES[ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES ][ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES ];

extern CcPieceTagType const CC_SETUP_BOARD_MAYAN_ASCENDANCY[ CC_VARIANT_BOARD_SIZE_MAYAN_ASCENDANCY ][ CC_VARIANT_BOARD_SIZE_MAYAN_ASCENDANCY ];

extern CcPieceTagType const CC_SETUP_BOARD_AGE_OF_AQUARIUS[ CC_VARIANT_BOARD_SIZE_AGE_OF_AQUARIUS ][ CC_VARIANT_BOARD_SIZE_AGE_OF_AQUARIUS ];

extern CcPieceTagType const CC_SETUP_BOARD_MIRANDAS_VEIL[ CC_VARIANT_BOARD_SIZE_MIRANDAS_VEIL ][ CC_VARIANT_BOARD_SIZE_MIRANDAS_VEIL ];

extern CcPieceTagType const CC_SETUP_BOARD_NINETEEN[ CC_VARIANT_BOARD_SIZE_NINETEEN ][ CC_VARIANT_BOARD_SIZE_NINETEEN ];

extern CcPieceTagType const CC_SETUP_BOARD_HEMERAS_DAWN[ CC_VARIANT_BOARD_SIZE_HEMERAS_DAWN ][ CC_VARIANT_BOARD_SIZE_HEMERAS_DAWN ];

extern CcPieceTagType const CC_SETUP_BOARD_TAMOANCHAN_REVISITED[ CC_VARIANT_BOARD_SIZE_TAMOANCHAN_REVISITED ][ CC_VARIANT_BOARD_SIZE_TAMOANCHAN_REVISITED ];

extern CcPieceTagType const CC_SETUP_BOARD_CONQUEST_OF_TLALOCAN[ CC_VARIANT_BOARD_SIZE_CONQUEST_OF_TLALOCAN ][ CC_VARIANT_BOARD_SIZE_CONQUEST_OF_TLALOCAN ];

extern CcPieceTagType const CC_SETUP_BOARD_DISCOVERY[ CC_VARIANT_BOARD_SIZE_DISCOVERY ][ CC_VARIANT_BOARD_SIZE_DISCOVERY ];

extern CcPieceTagType const CC_SETUP_BOARD_ONE[ CC_VARIANT_BOARD_SIZE_ONE ][ CC_VARIANT_BOARD_SIZE_ONE ];

// TODO :: DOCS
extern CcPieceTagType const CC_SETUP_BOARD_CLASSICAL_CHESS_14[ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS_14 ][ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS_14 ];

// TODO :: DOCS
extern CcPieceTagType const CC_SETUP_BOARD_CLASSICAL_CHESS_20[ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS_20 ][ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS_20 ];

// TODO :: DOCS
extern CcPieceTagType const CC_SETUP_BOARD_CLASSICAL_CHESS_26[ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS_26 ][ CC_VARIANT_BOARD_SIZE_CLASSICAL_CHESS_26 ];

// TODO :: DOCS
extern CcPieceTagType const CC_SETUP_BOARD_CROATIAN_TIES_14[ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES_14 ][ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES_14 ];

// TODO :: DOCS
extern CcPieceTagType const CC_SETUP_BOARD_CROATIAN_TIES_20[ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES_20 ][ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES_20 ];

// TODO :: DOCS
extern CcPieceTagType const CC_SETUP_BOARD_CROATIAN_TIES_26[ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES_26 ][ CC_VARIANT_BOARD_SIZE_CROATIAN_TIES_26 ];


CcPieceTagType const * cc_setup_board_get( CcVariantType ve );

CcMaybeBoolEnum cc_setup_board_has_piece( CcVariantType ve, CcPieceTagType pe );


#endif /* __CC_SETUP_BOARD_H__ */
