// Copyright (c) 2021 Mario Mlačak, mmlacak@gmail.com
// Licensed under 3-clause (modified) BSD license. See LICENSE for details.

#ifndef __SETUP_TAGS_H__
#define __SETUP_TAGS_H__


#include "tag_type.h"
#include "board_type.h"


extern TagType const SETUP_TAGS_CLASSICAL_CHESS[ BOARD_SIZE_CLASSICAL_CHESS ][ BOARD_SIZE_CLASSICAL_CHESS ];
extern TagType const SETUP_TAGS_CROATIAN_TIES[ BOARD_SIZE_CROATIAN_TIES ][ BOARD_SIZE_CROATIAN_TIES ];
extern TagType const SETUP_TAGS_MAYAN_ASCENDANCY[ BOARD_SIZE_MAYAN_ASCENDANCY ][ BOARD_SIZE_MAYAN_ASCENDANCY ];
extern TagType const SETUP_TAGS_AGE_OF_AQUARIUS[ BOARD_SIZE_AGE_OF_AQUARIUS ][ BOARD_SIZE_AGE_OF_AQUARIUS ];
extern TagType const SETUP_TAGS_MIRANDAS_VEIL[ BOARD_SIZE_MIRANDAS_VEIL ][ BOARD_SIZE_MIRANDAS_VEIL ];
extern TagType const SETUP_TAGS_NINETEEN[ BOARD_SIZE_NINETEEN ][ BOARD_SIZE_NINETEEN ];
extern TagType const SETUP_TAGS_HEMERAS_DAWN[ BOARD_SIZE_HEMERAS_DAWN ][ BOARD_SIZE_HEMERAS_DAWN ];
extern TagType const SETUP_TAGS_TAMOANCHAN_REVISITED[ BOARD_SIZE_TAMOANCHAN_REVISITED ][ BOARD_SIZE_TAMOANCHAN_REVISITED ];
extern TagType const SETUP_TAGS_CONQUEST_OF_TLALOCAN[ BOARD_SIZE_CONQUEST_OF_TLALOCAN ][ BOARD_SIZE_CONQUEST_OF_TLALOCAN ];
extern TagType const SETUP_TAGS_DISCOVERY[ BOARD_SIZE_DISCOVERY ][ BOARD_SIZE_DISCOVERY ];
extern TagType const SETUP_TAGS_ONE[ BOARD_SIZE_ONE ][ BOARD_SIZE_ONE ];


TagType const * const get_tags_setup( BoardType const bt );


#endif /* __SETUP_TAGS_H__ */
